export const FOOD_QUERY_ALIASES: Record<string, string[]> = {
    banana: ['банан', 'banana'],
    apple: ['яблоко', 'apple'],
    mandarin: ['мандарин', 'мандарины', 'tangerine', 'mandarin', 'clementine'],
    orange: ['апельсин', 'orange'],
    egg: ['яйцо', 'яйца', 'egg', 'eggs'],
    rice_cooked: ['рис', 'вареный рис', 'rice', 'rice cooked'],
    oatmeal_dry: ['овсянка', 'овсяные хлопья', 'oatmeal', 'oats'],
    beef_cooked: ['говядина', 'beef', 'cooked beef'],
    chicken_breast: ['курица', 'куриная грудка', 'chicken', 'chicken breast'],
    bell_pepper: ['болгарский перец', 'салатный перец', 'перец', 'bell pepper', 'sweet pepper'],
    carrot: ['морковь', 'carrot'],
    onion: ['лук', 'onion'],
    garlic: ['чеснок', 'garlic'],
    tomato: ['помидор', 'томат', 'tomato'],
    cucumber: ['огурец', 'cucumber'],
    spinach: ['шпинат', 'spinach'],
    potato: ['картофель', 'картошка', 'potato'],
    french_fries: ['картошка фри', 'фри', 'french fries', 'fries'],
    olive_oil: ['оливковое масло', 'масло оливковое', 'olive oil'],
    sunflower_oil: ['подсолнечное масло', 'sunflower oil'],
    butter: ['сливочное масло', 'butter'],
    bread: ['хлеб', 'bread'],
    yogurt: ['йогурт', 'yogurt'],
    milk: ['молоко', 'milk'],
    buckwheat_cooked: ['гречка', 'гречневая каша', 'buckwheat', 'buckwheat cooked'],
    pasta_cooked: ['паста', 'макароны', 'pasta', 'cooked pasta'],
    dill: ['укроп', 'dill'],
    parsley: ['петрушка', 'parsley'],
};